services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server1
    ports:
      - "8081:8080"
      - "2222:22"
    networks:
      - app-net

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server2
    ports:
      - "8082:8080"
      - "2223:22"
    networks:
      - app-net

networks:
  app-net:
